### ISSUE TITLE
Mix metadata

### ISSUE THREAD

**Issue by jb55** [id3/ID3v2.4#4]
There is a lot of rich mix metadata that is currently ignored by the current id3 spec. Some of the most common things people care about when listening to mixes are:
- What track is currently playing
- What are all the tracks in the mix, and at what times do they start

Typically this information is cataloged in a comment, but this isn't ideal. It would awesome if one day clients could support displaying which track is currently playing in a mix, as well as skipping to the next track.

Could this information (list of track titles and location) be implemented in the current spec? If so, what would be involved in putting such a proposal together?

Any feedback is appreciated!

Thanks

**Comment by lalinsky** [comment]
This is already supported by the `CHAP` frame - http://id3.org/id3v2-chapters-1.0

**Comment by jb55** [comment]
Oh, awesome. I didn't know that existed. Thanks!

**Comment by lalinsky** [comment]
Not many applications support it, but it solves exactly the problem you described.

**Comment by Crissov** [comment]
Still, the Chapters spec should become an integral part of ID3v2.
